# picolibrary-microchip-sam-d21da1
#
# Copyright 2023-2024, Andrew Countryman <apcountryman@gmail.com> and the
# picolibrary-microchip-sam-d21da1 contributors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
# file except in compliance with the License. You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the specific language governing
# permissions and limitations under the License.

# Description: GitHub Actions CI workflow for the picolibrary-microchip-sam-d21da1
#       repository.

name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    analyze-static-lizard:
        name: Analyze (static) - lizard
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - name: Analyze
              shell: bash
              run: ./ci/analyze --analyzer lizard

    analyze-static-shellcheck:
        name: Analyze (static) - shellcheck
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - name: Analyze
              shell: bash
              run: ./ci/analyze --analyzer shellcheck

    build-release-atsamd21g18a:
        name: Build (release-atsamd21g18a)
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - name: Install dependencies
              shell: bash
              run: sudo apt update && sudo apt install gcc-arm-none-eabi
            - name: Build
              shell: bash
              run: ./ci/build --configuration release-atsamd21g18a

    build-testing-interactive-atsamd21g18a-arduino-zero:
        name: Build (testing-interactive-atsamd21g18a-arduino-zero)
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - name: Install dependencies
              shell: bash
              run: sudo apt update && sudo apt install gcc-arm-none-eabi openocd
            - name: Build
              shell: bash
              run: ./ci/build --configuration testing-interactive-atsamd21g18a-arduino-zero

    format:
        name: Format
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - name: Configure dependencies
              shell: bash
              run: sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-10 100 && sudo update-alternatives --set clang-format /usr/bin/clang-format-10
            - name: Format
              shell: bash
              run: ./ci/format
